name: 6. Env. - Windows / EDGE, US-11.02.02/06
on:
  # push:
  workflow_dispatch:

permissions:
  contents: write

#  schedule:
#    - cron: '00 13 * * *'
#    - cron: '10 06 * * *'

jobs:
  tests:
    name: I. Building environment and testing the capital.com website
    #    runs-on: macos-latest
    #    runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: 1. Check out this repo, master branch
        uses: actions/checkout@v4
        with:
          ref: master
      #
      - name: 2.1. Install Python
        if: always()
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: 2.2. install Poetry
        if: always()
        run: pip3 install poetry

      - name: 2.3. install dependencies
        if: always()
        run: poetry update

      - name: 3. Run US_11-01-01 (Мила Д/Саша Т)
        if: always()
        run: poetry run pytest --no-summary -v tests/US_11_Education/US_11-01-01_Learning_hub/US_11-01-01_Learning_hub.py
        continue-on-error: true

#      - name: 3. Run US_11-02-02 test (Михаил)
#        if: always()
#        run: poetry run pytest --no-summary -v tests/US_11_Education/US_11-02-02_Shares_trading/US_11-02-02_Shares_trading_test.py
#        continue-on-error: true
#
#      - name: 4. Run US_11-02-02-01 test (Михаил)
#        if: always()
#        run: poetry run pytest --no-summary -v tests/US_11_Education/US_11-02-02_Shares_trading/US_11-02-02-01_Shares_trading_test.py
#        continue-on-error: true

#      - name: 5. Run US_11-01-06 (Сулейман/Андрей)
#        if: always()
#        run: poetry run pytest --no-summary -v tests/US_11_Education/US_11-01-06_investmate_app/us_11-01-06_investmate_app_test.py
#        continue-on-error: true

      - name: 6. Upload artifact "allure-results"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/
          retention-days: 15


  generate_report:
    name: II. Generate & Deploy Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ tests ]
    steps:
      - name: 1. Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 2. Download Artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: allure-results
          path: allure-results

      - name: 3. Create Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_history: allure-history
          allure_report: allure-report
          gh_pages: gh-pages
          #ref: gh-pages
          #path: gh-pages
          keep_reports: 30

      - name: 11.1 Deploy allure_report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: ./allure-history
          commit_message: ${{ github.event.head_commit.message }}
          # force_orphan: true

      - name: 5. Archive testing results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure_report
          path: allure_report

      - name: 12. Send telegram message on push
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
#           disable_web_page_preview: true
          message: |
            Message from GitHub CI Actions

            Testing of the "Capital.com" web application in the "Windows/Edge" environment is completed!

            See allure-result testing: https://${{ github.actor }}.github.io/SeleniumCapital/
            Tests Repository: ${{ github.repository }}
