name: Run Tests and Generate Allure Report Windows

on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"

      - name: 4. install Poetry
        if: always()
        run: pip3 install poetry

      - name: 5. install dependencies
        if: always()
        run: poetry update

      - name: 8. Run US_11-02-02 test (Михаил)
        if: always()
        run: poetry run pytest --no-summary -v tests/US_11_Education/US_11-02-02_Shares_trading/US_11-02-02_Shares_trading_test.py
        continue-on-error: true
#      - name: 8. Run US_11-02-02-01 test (Михаил)
#        if: always()
#        run: poetry run pytest --no-summary -v tests/US_11_Education/US_11-02-02_Shares_trading/US_11-02-02-01_Shares_trading_test.py
#        continue-on-error: true
#
      - name: 8. Upload artifact "allure-results"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 1




  allure-report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

#      - name: Install Allure Command-Line
#        run: |
#          sudo apt-get install default-jre
#          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
#          sudo dpkg -i allure_2.18.1-1_all.deb

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: allure-results

      - name: 9. Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 10. Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
          ref: gh-pages
          path: gh-pages
          keep_reports: 28

            #      - name: 11.1 Deploy report to Github Pages
            #        if: always()
            #        uses: peaceiris/actions-gh-pages@v2
            #        env:
            #          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #          PUBLISH_BRANCH: gh-pages
            #          PUBLISH_DIR: allure-history
            #
      - name: 11.1 Deploy allure_report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: ./allure-history
          commit_message: ${{ github.event.head_commit.message }}

