name: 3. Ubuntu, ReTests
on:
  # push:
  workflow_dispatch:

permissions:
  contents: write

#  schedule:
#    - cron: '00 13 * * *'
#    - cron: '10 06 * * *'

jobs:
  tests:
    name: I. Building environment and testing the capital.com website
    #    runs-on: macos-latest
    #    runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      #      - name: 1. Check out this repo
      #        uses: actions/checkout@v3
      #        continue-on-error: true

      - name: 1. Check out this repo, master branch
        uses: actions/checkout@v4
        with:
          ref: master
      #
      - name: 2.1. Install Python
        if: always()
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      #      - name: 3.1. Set up Homebrew
      #        id: set-up-homebrew
      #        uses: Homebrew/actions/setup-homebrew@master
      #
      #      - name: 3.3. Install Neofetch
      #        if: always()
      #        run: brew install neofetch

      - name: 2.2. install Poetry
        if: always()
        run: pip3 install poetry

      - name: 2.3. install dependencies
        if: always()
        run: poetry update

      - name: 8. Run WATC_ReTest
        if: always()
        continue-on-error: true
        #        run: poetry run pytest -vv tests/ReTests/WATC_ReTests.py
        run: poetry run pytest -vv tests/ReTests/ReTests.py
    #        run: poetry run pytest -n auto -vv tests/ReTests/WATC_ReTests.py


      - name: 8.1 Add allure information
        working-directory: allure-results
        if: always()
        run: |
          echo GIT_BRANCH=${{ github.head_ref || github.ref_name }}  >> environment.properties
          echo GIT_COMMIT_ID=${{ github.sha }} >> environment.properties
          echo GIT_COMMIT_MESSAGE=$(git show -s --format=%s HEAD) >> environment.properties
          echo GIT_COMMIT_AUTHOR_NAME=$(git show -s --format='%ae' HEAD) >> environment.properties
          echo GIT_COMMIT_TIME=$(git show -s --format=%ci HEAD) >> environment.properties
#          echo CHROME_VERSION=$(google-chrome --product-version) >> environment.properties


      - name: 9. Upload artifact "allure-results"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/
          retention-days: 10


  generate_report:
    name: II. Generate & Deploy Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ tests ]

    steps:
      - name: 1. Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 2. Download Artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: allure-results
          path: allure-results

      - name: 3. Create Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_history: allure-history
          allure_report: allure-report
          gh_pages: gh-pages
          #ref: gh-pages
          #path: gh-pages
          keep_reports: 30

      - name: 4. Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-history
          commit_message: ${{ github.event.head_commit.message }}

      - name: 5. Archive testing results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure_report
          path: allure_report

      - name: 12. Send telegram message on push
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
#           to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
#           disable_web_page_preview: true
          message: |
            Message from GitHub CI Actions

            Testing of the "Capital.com" web application in the "Windows/Edge" environment is completed!

            See allure-result testing: https://${{ github.actor }}.github.io/SeleniumCapital/
            Tests Repository: ${{ github.repository }}

